name: example
description: This is code generated via package:base_application/start.dart
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI 
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.5
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^1.1.6
  pull_to_refresh: ^2.0.0
  customized:
    git:
      url: https://github.com/srnunio/customized

  # Dependency Injection
  get_it: ^7.1.2
  injectable:

  # Dart data class
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  equatable: ^2.0.3

  # HTTP
  dio: ^5.0.2

  # Caching
  shared_preferences: ^2.0.13

  # State management
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  # Misc
  dartz: ^0.10.0-nullsafety.1
  intl: ^0.17.0 
  json_annotation: ^4.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.1
  json_serializable: ^6.6.1
  build_resolvers: ^2.0.1 
  gen_i18n: ^1.0.0
  
  # remove this 
  structorize:
    path: ../  

  # Testing
  mockito: ^5.0.10

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/locale/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
