name: structorize
description: With just a few commands I create all The structure needed to get your Flutter project ready to run.
version: 0.0.1
homepage: https://github.com/srnunio/structorize
repository: https://github.com/srnunio/structorize

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  path: ^1.8.0
  colorize: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
